# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-12-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canonical",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(blank=True, max_length=200, verbose_name="URL")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[[1, "Canonical"], [2, "Redirect"]], default=1, verbose_name="Kind"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.Product", verbose_name="Product"
                    ),
                ),
            ],
        ),
    ]
